name: "MultiQC - Linux"
on: [push, pull_request]

jobs:
  run_multiqc:
    name: Linux - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7]

    steps:

    # Check out MultiQC code
    - uses: actions/checkout@v1

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Update pip and install beautifulsoup4 for CI tests (CSP checking)
    - name: Install dependencies for CI tests
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade beautifulsoup4

    # Install MultiQC
    - name: Install MultiQC
      run: python setup.py install

    # Fetch the MultiQC test data
    - name: Download test data
      run: |
        git clone https://github.com/ewels/MultiQC_TestData.git test_data

    # Run all of the tests!
    - name: Special case input data
      run: multiqc test_data/data --ignore test_data/data/modules/

    - name: All modules / Custom report filename
      run: multiqc --lint test_data/data/modules/ --filename full_report.html

    - name: File-list input of dirs
      run: |
        cd test_data
        multiqc --file-list data/special_cases/dir_list.txt

    - name: Specific module / Force overwrite / Prepend dirnames / Name and comment / No data dir
      run: multiqc --lint test_data/data/modules/ -m fastqc -f -d -dd 1 -i "Forced Report" -b "This command has lots of options" --filename custom_fn --no-data-dir

    - name: For overwrite / Flat plots / Tagged modules only / Exclude module / Ignore samples / Full names / zip data dir / config file
      run: multiqc --lint test_data/data/modules/ -f --flat --tag methylation --exclude clusterflow --ignore-samples ngi --fullnames --zip-data-dir -c test/config_example.yaml

    - name: Specfic module / named output dir / dev template / JSON data / File list
      run: |
        cd test_data
        multiqc -m star -o tests/multiqc_report_dev -t default_dev -k json --file-list data/special_cases/file_list.txt

    - name: Empty directory
      run: |
        mkdir empty_dir
        multiqc -f empty_dir

    - name: Test for missing CSPs
      run: python test/print_missing_csp.py --report full_report.html --whitelist CSP.txt
